---
- block:
  - name: install iptables-persistent
    apt: name=iptables-persistent state=present
  - name: upload rules template
    template: src=rules.v4.j2 dest=/etc/iptables/rules.v4
  - name: reload rules
    command: netfilter-persistent reload
  become: yes
  become_method: sudo
