---
- name: start uwsgi
  service: name=curs  state=restarted
           enabled=yes
  become: yes
  become_method: sudo

- name: start nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  become_method: sudo

- name: start {{ service }}
  service: name={{ service }}  state=restarted
           enabled=yes
  become: yes
  become_method: sudo

- name: systemd {{ service }} start
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{ service }}"
  become: yes
  become_method: sudo