---
- name: start uwsgi
  service: name=curs  state=restarted
           enabled=yes
  become: yes
  become_method: sudo

- name: start nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  become_method: sudo

- name: start cursauto
  service: name=cursauto  state=restarted
           enabled=yes
  become: yes
  become_method: sudo