---
- block:
  - name: install python's repos
    apt_repository: repo='ppa:fkrull/deadsnakes'
  - name: install python3.6
    apt: name=python3.6  state=present
  - name: install python3.6-dev
    apt: name=python3.6-dev   state=present
    ########################
    # create user
    #######################
  - name: create app. user
    user: name={{ app_user }}
      comment="User for curs application"
      groups=www-data
      home={{ home_dir }}
      shell=/usr/sbin/nologin
  become: yes
  become_method: sudo
