---
- block:
  - name: create app. user
    user: name={{ app_user }}
      comment="User for curs application"
      groups=www-data
      home={{ home_dir }}
      shell=/usr/sbin/nologin

  - name: install "{{ python_ver }}-venv"
    apt: name=python3-venv  state=present
    
  - name: install python3-pip
    apt: name=python3-pip  state=present

  become: yes
