---
# install dpk packages (on Ubuntu)
- name: install python's repos
  apt_repository: repo='ppa:fkrull/deadsnakes'
- name: install python3.5
  apt: name=python3.5  state=present
- name: install python3.5-dev
  apt: name=python3.5-dev   state=present
- name: install mongo keys
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927
- name: instal mongodb apt_repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
    state=present
#    filename=mongodb-org-3.2
- name: install  mongodb-org
  apt: name=mongodb-org
    state=present
- name: install nginx
  apt: name=nginx state=present


...