---
- hosts: all
#  remote_user: vagrant
#  r_user: {{ remote_user }}
  vars:
    venv_dir: flask
    static_path: /var/www/curs/static
    home_dir: "{{ ansible_user_dir }}"
    app_file: curs-16.5.1.dev2.tar.gz
    conf_dir: /etc/curs
    ssl_certificate: /etc/nginx/ssl/nginx.crt
    ssl_certificate_key: /etc/nginx/ssl/nginx.key
  tasks:
    - block:
      - include: apts.yaml
        become: yes
        become_method: sudo
        when: ansible_pkg_mgr == "apt"
      - include: python.yaml
      - include: uwsgi_nginx.yaml
        become: yes
        become_method: sudo
      when: ansible_architecture == "x86_64"
  handlers:
    - include: handlers/handlers.yml
...