---
- hosts: all
  vars_files:
    - vars/main.yml
  tasks:
  # ------- stop services -----------
    - block:
      - name: stop curs.service
        service: name=curs  state=stopped
      - name: stop cursauto.service
        service: name=cursauto  state=stopped
      become: yes
      become_method: sudo

      # remove app from venv and home dir
    - block:
      - name: remove application from env
        pip: name=curs
             virtualenv={{ home_dir }}/{{ venv_dir }}
             virtualenv_python=python3.5
             state=absent
      - name: delete previos file package
        file: name=/{{ home_dir }}/{{ app_file }}
          state=absent
      become: yes
      become_user: "{{ app_user }}"
      become_method: sudo