---
- hosts: all
  vars:
#    ssl_certificate_key: /etc/nginx/ssl/nginx.key
  vars_files:
    - vars/main.yml
  roles:
# or put in meta into dependencies:
    - mongodb
    - python3
    - role: nginx
      tags:
        - nginx
    - role: curs
      tags:
        - curs

