all:
  children:
    gcp:
      hosts:
        f1-monga:
          ansible_host: "{{ f1_monga }}"
          ansible_user: vic
          ansible_python_interpreter: /usr/bin/python3
    local:
      hosts:
        127.0.0.1:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
