---
- name: prepare config mongodb.service
  template: src=templates/mongodb.service.j2 dest=/etc/systemd/system/mongodb.service
  when: ansible_service_mgr == "systemd"
- name: start mongo (systemd)
  systemd: name=mongodb state=stopped enabled=yes
  when: ansible_service_mgr == "systemd"
- name: start mongo (init)
  service: name=mongod state=started enabled=yes
  when: ansible_service_mgr == "upstart"


