---
- name: prepare config mongodb.service
  template: src=mongodb.service.j2 dest=/etc/systemd/system/mongodb.service
  when: ansible_service_mgr == "systemd"
  become: yes
  become_method: sudo
- name: prepare config mongod.conf
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  become: yes
  become_method: sudo
- name: start mongodb
  service: name=mongodb state=started enabled=yes
  become: yes
  become_method: sudo