handlers:
  - name: start uwsgi
    service: name=curs  state=started
             enabled=yes
    become: yes
    become_method: sudo
  - name: start nginx
    service: name=nginx state=restarted
             enabled=yes
    become: yes
    become_method: sudo
  - name: prepare config mongodb.service
    template: src=templates/mongodb.service.j2 dest=/etc/systemd/system/mongodb.service
    when: ansible_service_mgr == "systemd"
  - name: start mongodb
    service: name=mongodb state=started enabled=yes
    become: yes
    become_method: sudo
