---
- name: start mongo
  service: name=mongod state=started
           enabled=yes
  become: yes
  become_method: sudo
- name: start uwsgi
  service: name=curs  state=started
           enabled=yes
  become: yes
  become_method: sudo
- name: start nginx
  service: name=nginx state=restarted
           enabled=yes
  become: yes
  become_method: sudo