---
venv_dir: flask
home_dir: "{{ ansible_user_dir }}"
cursauto: bin/curs_auto
app_file: curs-16.5.1.dev3.tar.gz
conf_dir: /etc/curs
# nginx
static_path: /var/www/curs/static
ssl_certificate: /etc/nginx/ssl/nginx.crt
ssl_certificate_key: /etc/nginx/ssl/nginx.key