---
#- name: start {{ service }}
#  service: name={{ service }}  state=restarted
#           enabled=yes
#  become: yes
#  become_method: sudo

- name: systemd {{ service }} start
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{ service }}"
  become: yes
  become_method: sudo
# --------- Reload systemd, scanning for new or changed units ---
# looks it not need starting ansible 2.2.1
#- name:  reload systemd
#  command: systemctl daemon-reload
#  become: yes
#  become_method: sudo