---
- name: start {{ service }}
  service: name={{ service }}  state=restarted
           enabled=yes
  become: yes
  become_method: sudo

#- name: start nginx
#  service: name=nginx state=restarted enabled=yes
#  become: yes
#  become_method: sudo
#
#- name: start cursauto
#  service: name=cursauto  state=restarted
#           enabled=yes
#  become: yes
#  become_method: sudo

# --------- Reload systemd, scanning for new or changed units ---
- name:  reload systemd
  command: systemctl daemon-reload
  become: yes
  become_method: sudo