---
- block:
  - name: install mongo keys
    apt_key: keyserver=keyserver.ubuntu.com id=EA312927
  - name: instal mongodb apt_repository
    apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
      state=present
  #    filename=mongodb-org-3.2
  - name: install  mongodb-org
    apt: name=mongodb-org state=present
    notify:
      - prepare config mongodb.service
      - start mongodb
  become: yes
  become_method: sudo
