---
- block:
  - name: install mongo keys
    apt_key: keyserver=keyserver.ubuntu.com id=EA312927
  - name: instal mongodb apt_repository
    apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
      state=present
      update_cache=yes
  #    filename=mongodb-org-3.2
  # for linux only 64-bits available
  # manual install https://fastdl.mongodb.org/linux/mongodb-linux-i686-3.2.10.tgz
  # https://gkbrown.org/2016/03/31/installing-mongodb-on-32-bit-ubuntu-15-10/
#  - name: install  mongodb-org
#    apt: name=mongodb-org state=present
#    notify:
#      - prepare config mongodb.service
#      - start mongodb
  become: yes
  become_method: sudo
