---
- block:
  - name: install mongo keys
    shell:
      cmd: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - name: Create a list file for MongoDB
    shell:
      cmd: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

  - name: update repo
    apt_repository:
      repo='deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'
      update_cache=yes
      
  - name: update and upgrade repo
    apt:
      upgrade: yes
      update_cache: yes

  - name: install  mongodb-org
    apt: name=mongodb-org state=present
    notify:
      - prepare config mongodb.service
      - prepare config mongod.conf
      - start mongodb

  - name: create directory for mongo
    file:
      path: /data/mongodb
      state: directory
      owner: mongodb
      group: nogroup
      mode: 0700

  become: yes
  become_method: sudo
  when: ansible_architecture != "i386"